# Generated by Django 2.1 on 2018-08-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('report_title', models.IntegerField()),
                ('report_slug', models.IntegerField()),
                ('report_discription', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'report',
                'managed': False,
            },
        ),
    ]
